# Generated by Django 5.1.4 on 2025-01-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_label_membership_task_label_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='label_set',
            new_name='labels',
        ),
    ]
